os:
  - linux
#  - osx

language: cpp

compiler:
  - gcc
  - clang

before_install:
  - mkdir tmp
#; if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then brew update; fi

python:
  - "2.7"

addons:
    apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - libboost-thread-dev 
          - libboost-system-dev
          - libboost-filesystem-dev
          - libboost-test-dev
          - libfuse-dev
          - gcc-4.8
          - g++-4.8
          - clang


install:
  - if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then sudo apt-get install -qq valgrind astyle; fi
  
#  - if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then brew upgrade boost; fi
#  - if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then brew install doxygen valgrind astyle openssl; fi
  
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8" CMAKE_CXX_COMPILER="g++-4.8" CMAKE_C_COMPILER="gcc-4.8"; fi ; ./build-debug.sh

#matrix:
#    exclude:
#        - os: osx
#          compiler: gcc


script:
  - ctest --extra-verbose --output-on-failure
  ##- if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then for f in ./build/test/*; do valgrind --leak-check=full --show-reachable=no --error-exitcode=1 "$f"; done; fi
  #- if make tidy | grep "Formatted " ; then exit 2; else echo "No changes found by astyle" ; make tidy; fi;

# DEfault method hides error messages for certain imports
# ; python setup.py test


notifications:
  email: false

# whitelist
#branches:
#  only:
#    - master
