#include <iostream>
#include <fstream>

#include "two_bit_byte.hpp"

const char two_bit_byte::hash_table[(256*4) + 1] = "TTTTTTTCTTTATTTGTTCTTTCCTTCATTCGTTATTTACTTAATTAGTTGTTTGCTTGATTGGTCTTTCTCTCTATCTGTCCTTCCCTCCATCCGTCATTCACTCAATCAGTCGTTCGCTCGATCGGTATTTATCTATATATGTACTTACCTACATACGTAATTAACTAAATAAGTAGTTAGCTAGATAGGTGTTTGTCTGTATGTGTGCTTGCCTGCATGCGTGATTGACTGAATGAGTGGTTGGCTGGATGGGCTTTCTTCCTTACTTGCTCTCTCCCTCACTCGCTATCTACCTAACTAGCTGTCTGCCTGACTGGCCTTCCTCCCTACCTGCCCTCCCCCCCACCCGCCATCCACCCAACCAGCCGTCCGCCCGACCGGCATTCATCCATACATGCACTCACCCACACACGCAATCAACCAAACAAGCAGTCAGCCAGACAGGCGTTCGTCCGTACGTGCGCTCGCCCGCACGCGCGATCGACCGAACGAGCGGTCGGCCGGACGGGATTTATTCATTAATTGATCTATCCATCAATCGATATATACATAAATAGATGTATGCATGAATGGACTTACTCACTAACTGACCTACCCACCAACCGACATACACACAAACAGACGTACGCACGAACGGAATTAATCAATAAATGAACTAACCAACAAACGAAATAAACAAAAAAAGAAGTAAGCAAGAAAGGAGTTAGTCAGTAAGTGAGCTAGCCAGCAAGCGAGATAGACAGAAAGAGAGGTAGGCAGGAAGGGGTTTGTTCGTTAGTTGGTCTGTCCGTCAGTCGGTATGTACGTAAGTAGGTGTGTGCGTGAGTGGGCTTGCTCGCTAGCTGGCCTGCCCGCCAGCCGGCATGCACGCAAGCAGGCGTGCGCGCGAGCGGGATTGATCGATAGATGGACTGACCGACAGACGGAATGAACGAAAGAAGGAGTGAGCGAGAGAGGGGTTGGTCGGTAGGTGGGCTGGCCGGCAGGCGGGATGGACGGAAGGAGGGGTGGGCGGGAGGGG" ;

void two_bit_byte::set(unsigned char bit_offset, unsigned char nucleotide)
{
	// byte_offset must be: {0, 2, 4 or 6};
	// nucleotides must be:
	// => T - 00, C - 01, A - 10, G - 11
	// => T - 00, C -  1, A -  2, G -  3
	
	this->data |= (unsigned char) (nucleotide << bit_offset);
};

void two_bit_byte::print()
{
	// leuk, testen!
	char c1 = two_bit_byte::hash_table[this->data * 4];
	char c2 = two_bit_byte::hash_table[(this->data * 4) + 1] ;
	char c3 = two_bit_byte::hash_table[(this->data * 4) + 2] ;
	char c4 = two_bit_byte::hash_table[(this->data * 4) + 3] ;
	printf("[%i] -> %c%c%c%c\n", this->data , c1 ,c2 ,c3 ,c4);
	
}
